### ISSUE TITLE
Thiết kế class diagram

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#11]
- [x] 26/03/2023: Thiết kế class User
- [x] 27/03/2023: Thiết kế class Camera
- [x] 28/03/2023: Thiết kế class Area
- [x] 29/03/2023: Thiết kế class Alert
- [x] 30/03/2023: Thiết kế class Statistic

**Comment by binh0804** [comment]
Link tài liệu: https://docs.google.com/document/d/1p4TopyZciONF3rnBeORXW3zxLwfqW63TT-pg2BtpNAE/edit?usp=sharing

**Comment by binh0804** [comment]
Hoàn thành task 1,2. Đã bổ sung vào tài liệu nêu trên.

**Comment by hualocson** [comment]
Hoàn thành vẽ usecase

**Comment by hualocson** [comment]
Link usecase diagram: https://drive.google.com/file/d/1lgtzlBeWnuIWvNtQuo6jQyFXeaYSN48F/view?usp=sharing
