### ISSUE TITLE
Xây dựng SRS: Overall Description (Section 02)

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#13]
- [x] 27/03/2023: Product Perspective
- [x] 28/03/2023: Product Features
- [x] 29/03/2023: User Classes and Characteristics
- [x] 29/03/2023: Operating Environment
- [x] 30/03/2023: Design and Implementation Constraints
- [x] 30/03/2023: User Documentation
- [x] 31/03/2023: Assumptions and Dependencies

**Comment by NhatNguyencute** [comment]
27/03/2023: Product Perspective
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
28/03/2023: Product Features
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
29/03/2023: User Classes and Characteristics
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
29/03/2023: Operating Environment
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
30/03/2023: Design and Implementation Constraints
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
30/03/2023: User Documentation
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
31/03/2023: Assumptions and Dependencies
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1
