### ISSUE TITLE
Xây dựng SRS: System Features (Section 03) | Part 1: Chức năng Đăng nhập 

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#14]
1. Chức năng Đăng nhập
- [x] Task 18/03/2023: Description and Priority
- [x] Task 18/03/2023: Stimulus/Response Sequences
- [x] Task 19/03/2023: Vẽ Activity Diagram

**Comment by hualocson** [comment]
Done
