### ISSUE TITLE
Xây dựng SRS: Other Nonfunctional Requirements (Section 05)

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#16]
- [x] 01/04/2023: Performance Requirements
- [x] 01/04/2023: Safety Requirements
- [x] 02/04/2023: Security Requirements
- [x] 03/04/2023: Software Quality Attributes

**Comment by NhatNguyencute** [comment]
01/04/2023: Performance Requirements
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
01/04/2023: Safety Requirements
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
02/04/2023: Security Requirements
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1

**Comment by NhatNguyencute** [comment]
03/04/2023: Software Quality Attributes
https://docs.google.com/document/d/1ZlmoPep9xexqkBOtdRrDjttcVzbrJwqc/edit#heading=h.2s8eyo1
