### ISSUE TITLE
Xây dựng SRS: System Features (Section 03) | Part 2: Chức năng Xem danh sách Camera

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#17]
2. Chức năng Xem danh sách Camera
- [x] Task 19/03/2023: Description and Priority
- [x] Task 20/03/2023: Stimulus/Response Sequences
- [x] Task 20/03/2023: Vẽ Activity Diagram

**Comment by hualocson** [comment]
Done
