### ISSUE TITLE
Xây dựng SRS: System Features (Section 03) | Part 3: Chức năng Xem các cảnh báo

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#18]
3. Chức năng Xem các cảnh báo
- [x] Task 21/03/2023: Description and Priority
- [x] Task 21/03/2023: Stimulus/Response Sequences
- [x] Task 22/03/2023: Vẽ Activity Diagram

**Comment by hualocson** [comment]
Done
