### ISSUE TITLE
Xây  dựng UI WarningPage

### ISSUE THREAD

**Issue by hualocson** [binh0804/AI-Camera-Dashboard#42]
- [x] Task ngày 09/04/2023: Xây  dựng UI WarningPage - xây dựng jsx
- [x] Task ngày 10/04/2023: Xây  dựng UI LoadingPage - xây dựng css

**Comment by NhatNguyencute** [comment]
Hoàn thành. Link code: https://github.com/binh0804/AI-Camera-Dashboard-with-Django
