### ISSUE TITLE
Deploy Project: Tìm hiểu về Docker và các khái niệm cơ bản

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#57]
- [x] Task ngày 18/04/2023: Tìm hiểu về Docker và các khái niệm cơ bản

**Comment by NhatNguyencute** [comment]
Task ngày 18/04/2023: Tìm hiểu về Docker và các khái niệm cơ bản
https://docs.google.com/document/d/1fbqSqO0HOrSRFUVzBTKWpiE4OvfxShhLDNaw3jLpO5Y/edit?usp=sharing
