### ISSUE TITLE
Deploy Project: Tìm hiểu cách xây dựng image từ Dockerfile

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#58]
- [x] Task ngày 19/04/2023: Tìm hiểu cách xây dựng image từ Dockerfile

**Comment by NhatNguyencute** [comment]
Task ngày 19/04/2023: Tìm hiểu cách xây dựng image từ Dockerfile
https://docs.google.com/document/d/1-hQCKmctQkU3AN7V_6W3JTzaxI9YYP68ARPDLRUZclk/edit?usp=sharing
