### ISSUE TITLE
Deploy Project: Tìm hiểu cách đẩy image lên Docker Hub

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#59]
- [x] Task ngày 20/04/2023: Tìm hiểu cách đẩy image lên Docker Hub

**Comment by NhatNguyencute** [comment]
Task ngày 20/04/2023: Tìm hiểu cách đẩy image lên Docker Hub
https://docs.google.com/document/d/1yXaAzzyBCMZrARfSbKYE2q1lO093mS37tOxMwxsvbpU/edit?usp=sharing
