### ISSUE TITLE
Deploy Project: Tìm hiểu về EC2 và cách tạo instane EC2 trên AWS

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#60]
- [x] Task ngày 21/04/2023: Tìm hiểu về EC2 và cách tạo instane EC2 trên AWS

**Comment by NhatNguyencute** [comment]
Task ngày 21/04/2023: Tìm hiểu về EC2 và cách tạo instane EC2 trên AWS
https://docs.google.com/document/d/1JfPpcKOc6FPH2t2kbD8c5T3Pv95-rlScxxXuUXLFpmk/edit?usp=sharing
