### ISSUE TITLE
Deploy Project: Tìm hiểu cách khởi chạy container trên instance EC2

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#61]
- [x] Task ngày 22/04/2023: Tìm hiểu cách khởi chạy container trên instance EC2

**Comment by NhatNguyencute** [comment]
Task ngày 22/04/2023: Tìm hiểu cách khởi chạy container trên instance EC2
https://docs.google.com/document/d/1wxJ3RyVLnBZN2kOV_bohHknNUVse0CrD1xOHxC3cIoo/edit?usp=sharing
