### ISSUE TITLE
Deploy Project: Tìm hiểu các rủi ro có thể phát sinh khi deploy project trên AWS với EC2

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#62]
- [x] Task ngày 23/04/2023: Tìm hiểu các rủi ro có thể phát sinh khi deploy project trên AWS với EC2

**Comment by NhatNguyencute** [comment]
Task ngày 23/04/2023: Tìm hiểu các rủi ro có thể phát sinh khi deploy project trên AWS với EC2
https://docs.google.com/document/d/1O4yEwDDRoA8v7OzzqJLRSOx45bFsz5rmcXE1U7JzabQ/edit?usp=sharing
