### ISSUE TITLE
Deploy Project: Viết báo cáo về việc khởi chạy project trên localhost

### ISSUE THREAD

**Issue by binh0804** [binh0804/AI-Camera-Dashboard#63]
- [x] Task ngày 24/04/2023: Viết báo cáo về việc khởi chạy project trên localhost

**Comment by NhatNguyencute** [comment]
Task ngày 24/04/2023: Viết báo cáo về việc khởi chạy project trên localhost
https://docs.google.com/document/d/1HeGiGs_l1R9NEZDepZorjO5AnwoDH39lO4kR_QQhWdg/edit?usp=sharing
